title: "Oh To Be Software"
description: "Oh to be a monkeyâ€¦ writing great code."
# theme: jekyll-theme-minimal
remote_theme: pages-themes/dinky@v0.2.0
# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one

markdown: kramdown

url: "https://oh2bamonkey.com"
github_username: "oh2bamonkey"
